// Country-name + flag lookup keyed by ISO-2 (lowercase input OK).
// Same source for both WorldMap2D (selected) and TopCountriesTable (panel).
export const COORD_NAMES: Record<string, { name: string; flag: string }> = {
  US: { name: 'United States',     flag: '🇺🇸' },
  CN: { name: 'China',             flag: '🇨🇳' },
  RU: { name: 'Russia',            flag: '🇷🇺' },
  DE: { name: 'Germany',           flag: '🇩🇪' },
  BR: { name: 'Brazil',            flag: '🇧🇷' },
  IN: { name: 'India',             flag: '🇮🇳' },
  GB: { name: 'United Kingdom',    flag: '🇬🇧' },
  FR: { name: 'France',            flag: '🇫🇷' },
  JP: { name: 'Japan',             flag: '🇯🇵' },
  KR: { name: 'South Korea',       flag: '🇰🇷' },
  AU: { name: 'Australia',         flag: '🇦🇺' },
  NL: { name: 'Netherlands',        flag: '🇳🇱' },
  UA: { name: 'Ukraine',           flag: '🇺🇦' },
  SG: { name: 'Singapore',         flag: '🇸🇬' },
  ID: { name: 'Indonesia',         flag: '🇮🇩' },
  VN: { name: 'Vietnam',           flag: '🇻🇳' },
  TH: { name: 'Thailand',          flag: '🇹🇭' },
  TR: { name: 'Turkey',            flag: '🇹🇷' },
  SA: { name: 'Saudi Arabia',      flag: '🇸🇦' },
  MX: { name: 'Mexico',            flag: '🇲🇽' },
  AR: { name: 'Argentina',         flag: '🇦🇷' },
  ZA: { name: 'South Africa',      flag: '🇿🇦' },
  NG: { name: 'Nigeria',           flag: '🇳🇬' },
  EG: { name: 'Egypt',             flag: '🇪🇬' },
  IL: { name: 'Israel',            flag: '🇮🇱' },
  PL: { name: 'Poland',            flag: '🇵🇱' },
  IT: { name: 'Italy',             flag: '🇮🇹' },
  ES: { name: 'Spain',             flag: '🇪🇸' },
  CA: { name: 'Canada',            flag: '🇨🇦' },
  SE: { name: 'Sweden',            flag: '🇸🇪' },
  IR: { name: 'Iran',              flag: '🇮🇷' },
  IQ: { name: 'Iraq',              flag: '🇮🇶' },
  PK: { name: 'Pakistan',         flag: '🇵🇰' },
  BD: { name: 'Bangladesh',        flag: '🇧🇩' },
  ET: { name: 'Ethiopia',          flag: '🇪🇹' },
  KE: { name: 'Kenya',             flag: '🇰🇪' },
  DZ: { name: 'Algeria',           flag: '🇩🇿' },
  MA: { name: 'Morocco',           flag: '🇲🇦' },
  LY: { name: 'Libya',             flag: '🇱🇾' },
  SD: { name: 'Sudan',             flag: '🇸🇩' },
  YE: { name: 'Yemen',             flag: '🇾🇪' },
  HK: { name: 'Hong Kong',         flag: '🇭🇰' },
  TW: { name: 'Taiwan',            flag: '🇹🇼' },
  MY: { name: 'Malaysia',          flag: '🇲🇾' },
  PH: { name: 'Philippines',       flag: '🇵🇭' },
  IE: { name: 'Ireland',           flag: '🇮🇪' },
  CH: { name: 'Switzerland',       flag: '🇨🇭' },
  AT: { name: 'Austria',           flag: '🇦🇹' },
  BE: { name: 'Belgium',           flag: '🇧🇪' },
  CZ: { name: 'Czech Republic',    flag: '🇨🇿' },
  GR: { name: 'Greece',            flag: '🇬🇷' },
  HU: { name: 'Hungary',           flag: '🇭🇺' },
  RO: { name: 'Romania',           flag: '🇷🇴' },
  PT: { name: 'Portugal',          flag: '🇵🇹' },
  KZ: { name: 'Kazakhstan',        flag: '🇰🇿' },
  VE: { name: 'Venezuela',         flag: '🇻🇪' },
  CL: { name: 'Chile',             flag: '🇨🇱' },
  CO: { name: 'Colombia',          flag: '🇨🇴' },
  PE: { name: 'Peru',              flag: '🇵🇪' },
  CU: { name: 'Cuba',              flag: '🇨🇺' },
  NO: { name: 'Norway',            flag: '🇳🇴' },
  FI: { name: 'Finland',           flag: '🇫🇮' },
  DK: { name: 'Denmark',           flag: '🇩🇰' },
  NZ: { name: 'New Zealand',       flag: '🇳🇿' },
  UNKNOWN: { name: 'Unknown',        flag: '🌐' },
}
